name = "soc-infra"
type = "javascript"
compatibility_date = "2024-01-28"

[env.production]
name = "soc-infra-production"

[build]
command = "cd frontend && npm install && npm run build"
cwd = "."
watch_paths = ["frontend/**/*.{js,jsx,ts,tsx,css}"]

[env.production.build]
command = "cd frontend && npm install && npm run build"

[[env.production.routes]]
pattern = "relearn.org.in"
